### PR TITLE
Add rolling-rhino Go codebase

### PR DESCRIPTION
**Pull request by nickgerace**
Hi all. Great work on this @flexiondotorg, and to all the other contributors as well.

Since rolling-rhino is getting a lot of contributions and attention, I thought I'd throw the following idea in the ring.
I believe that a compiled language (like Go) could work really well for this project in the long term.

Rather than create a fork, I wanted to put out this PR to see what the maintainers and community think.
_It's not perfect, and was made for fun_, but I thought I'd share the current progress nonetheless!

Of course, if it's not what anyone is looking for, then that is totally fine. Suggestions, comments, etc. are welcome. Thank you.

Nick

### CODE REVIEW

**Comment by nickgerace** [comment]
Here is the STDOUT from the "make docker" build and execution. Currently, I have the Dockerfile skipping confirmations and desktop detection.

```
[nick@thinkpad:~/rolling-rhino/go on master]
% make docker
cd /home/nick/rolling-rhino/go; go fmt ./...
cd /home/nick/rolling-rhino/go; go vet ./...
cd /home/nick/rolling-rhino/go; go test ./...
?       github.com/wimpysworld/rolling-rhino    [no test files]
cd /home/nick/rolling-rhino/go; go build -o rhinoctl
cd /home/nick/rolling-rhino/go; docker build .
Sending build context to Docker daemon   2.65MB
Step 1/5 : FROM ubuntu:devel
 ---> 73bfdffe747e
Step 2/5 : RUN apt update     && apt install -y lsb-release
 ---> Using cache
 ---> 9c2d8b6368fc
Step 3/5 : WORKDIR /app
 ---> Using cache
 ---> 74cc4d8a08e6
Step 4/5 : COPY rhinoctl /app
 ---> d34f0cf934b8
Step 5/5 : RUN /app/rhinoctl -f -d
 ---> Running in 3c0ea1fb862f
Rolling Rhino 🦏
  [+] INFO: lsb_release detected.
  [+] INFO: Ubuntu detected.
  [+] INFO: Ubuntu Groovy Gorilla (development branch) detected.
  [+] INFO: No PPAs detected, this is good.
  [+] INFO: All checks passed.
  [+] INFO: Switching to devel series.
  [+] INFO: Finished task: autoclean
  [+] INFO: Finished task: clean
  [+] INFO: Finished task: update
  [+] INFO: Finished task: dist-upgrade
  [+] INFO: Finished task: autoremove
  [+] INFO: Your Rolling Rhino is ready.
Removing intermediate container 3c0ea1fb862f
 ---> ed2b5e4fbcb6
Successfully built ed2b5e4fbcb6
```

**Comment by bigpod98** [comment]
well if i may add my 2 cents using compiled language here isnt that important since this is realy just executing bunch of shell commands

**Comment by nickgerace** [comment]
@bigpod98 For this PR as it stands, I agree with you, and appreciate the input! I agree especially since the environment here is pretty much always certain: Ubuntu with Bash.

However, this is the first "ported" version, so I kept a lot of the subcommands. I'm wonder if having a binary instead could slowly phase out reliance on lsb_releaee, for example.

Plus, I wonder if this could yield access to more testing strategies, error handling, advanced CPU arch handling, and the ability to have the binary act as an "on/off" switch for rolling-rhino. Maybe with subcommands too, like "clean", which restores the sources.list to its original rolling-rhino value.

Those things are what pushed me to create the PR. Though, perhaps it would have more value to replace those subcommands now rather than later.

**Comment by bigpod98** [comment]
well yes if you in theory could move away from basicly executing shell commands then it might be somewhat usefull but as it stands its basicly execute shell comands and few logic statements

**Comment by nickgerace** [comment]
That's fair. I'll close this PR for now and then reopen if I refactor it. I agree though. Thank you for the review!

**Pull request closed without merging**
